apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: context-broker
    includeSelectors: true
    includeTemplates: false

resources:
- ../../base/

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: context-broker
  path: patches/image.yaml
